### PR TITLE
WCM-747

### PR DESCRIPTION
**Pull request by ericyanLr**
Hello,

**Original LPS Ticket:** [LPP-21588](https://issues.liferay.com/browse/LPP-21588)
**WCM Ticket:** [WCM-747](https://issues.liferay.com/browse/WCM-747)

Here is a pull request to resolve issues with browser compatibility (IE7) that I found during startup.

**Note**
- I do not know how to generate **analytics.min.js**, so this commit only has changes to **analytics.js**
- Also, I had to modify **docroot/css/ct_simulator/main.css** in order to make it compile
    - I had to add **@import "mixins";** to the top of the page, but I did not include this in the PR.

If there is anything that I need to change, please let me know.
Thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Thanks a lot @ericyanLr! We have generated the minified version of analytics.js

Regarding the import mixins line, I can see that line in ct_simulator.css... maybe we are looking at different files? 

https://github.com/liferay/liferay-apps-content-targeting/blob/6.2.x/1.x/content-targeting-web/docroot/css/ct_simulator/main.css

**Comment by ericyanLr** [comment]
Hey @juliocamarero,

You're right, it was actually the [main.css](https://github.com/liferay/liferay-apps-content-targeting/blob/master/content-targeting-web/docroot/css/ct_simulator/main.css) in the master branch that had the missing import mixins line.

**Quick Question for General Fix Delivery**
Just to confirm, to deliver this fix, should we wait for the latest release that the team releases every few months and ask the customer to download the latest version on the marketplace?

Also, would this fix also be included in the EE version or would we have the customer download the CE version?

Thanks Julio!

**Comment by juliocamarero** [comment]
moving to email :)

**Pull request merged**
