### PR TITLE
WCM-353 Show both name and description when selecting user group in rule

### PR DESCRIPTION
**Pull request by deadcyclo**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @deadcyclo,

We understand the problem you are trying to solve, but adding the whole description to the Select can get very nasty if the description is very long.

Maybe limiting the size of the description to a maximun number of characters could solve that...

Another issue we see is that we have a similar selector for Roles, Sites, Organizations... and all those could have a description too. We should probably apply the same solution to all of them.

A nice solution (which is harder for sure) would be to display a really nice User Group Selector as we do in the User Administration (Users & Organizations > Edit > User Groups) which would display both title and description, pagination, search... etc in a popup.

Again, if we apply this pattern we should apply to all the rules and not only the User Groups one.
How would you feel about this?

test_test_-_users_and_organizations_-_liferay


Thanks a lot!

**Comment by deadcyclo** [comment]
Indeed. That was just a quick fix for a customer done right before leaving work today. 

It just so happens that my wife is gone at a conference this coming weekend, so I might be able to contribute a much more solid solution this weekend. I'll let you know this weekend what I come up with.

I'm guessing that limiting characters and implementing for both roles, sites and organizations is a nice "quick fix" start seeing as that should take no time what so ever to implement. The nice select feature naturally would be a much better permanent solution. Uncertain how much work it would be, but potentially it would only have to involve a struts action url opened in a modal window?

**Comment by JorgeFerrer** [comment]
Hey Julio,

May I propose not using columns for this? I know this is a common pattern in the product, but if the name is large then the description column ends up being too narrow and too long (even if you limit the size).

Instead I would put it until the title (in the same column) with an smaller and dimmer font.

Thoughts?

**Comment by deadcyclo** [comment]
@JorgeFerrer 

Isn't it better to re-use the existing components from the control panel? If I'm not completely mistaken (without having investigated the code properly yet) that should be simle using a modal window that calls a struts action and implementing the right javascript callback. And rather fix the column issue in the original components.

The reason I suggest this is because the component fragmentation  is one of the few things that really bugs me about Liferay. There are lots of different implementations of components that do the exact same thing throughout the portal. All of them different, and all of them with their own drawbacks and benefits. This gets really confusing and annoying for front-end users. An example is asset selection which exists in at least three (probably more though) forms in the portal.

**Comment by juliocamarero** [comment]
Hi @JorgeFerrer ,

I do like your proposal since it has many UX benefits compared to the current one, but I would keep that change for 7.0 instead of applying it here for several reasons:
- consistency: it would be strange that the UI to select user groups is different depending on which application you selecting them
- reutilization: right now, that UI is part of the User Groups Admin portlet and therefore we can simply reuse it. Having a different UI would force us to implement a User Group browser UI.

What do you think?

**Comment by JorgeFerrer** [comment]
Sounds good

--
Jorge Ferrer

**Comment by deadcyclo** [comment]
Uhu. Instead of doing dev work I ended up sick with the flu for a week and a half while I was alone home. So I'll try to get back to this a bit later

**Comment by juliocamarero** [comment]
ouch, sorry about that. Hope you are feeling better now! :+1:

**Comment by deadcyclo** [comment]
I've unfortunately got bad news here. I spent a few hours now investigating this, and our suggestion won't work. It's not possible to re-use the functionality from other places in the portal as I suggested. The reason is that its quite possible (actually quite probable as well) for users to have access to making content targeting rules, but not have view access to the User Admin portlet which contains the user group/role/site/organization selectors.

**Comment by deadcyclo** [comment]
But on second though. This might actually be more correct. The current solution sort of bypasses Liferays security system by allowing users that don't have view access to user groups to select user groups. Theoretically this is wrong, in my honest opinion.

**Comment by juliocamarero** [comment]
Hey @deadcyclo 

the permissions issue that you mention is a hard issue we also found during development. We tried to use all the remote services (checking permissions for the rules to select) here: https://issues.liferay.com/browse/WCM-126

however, for some services the Remote API didn't expose that functionality and therefore we couldn't filter by permissions. 

We will be able to fix those in future versions of the product.

**Comment by juliocamarero** [comment]
Regarding the portlet, it should behave in a similar way to the portlet "users admin" which also allows users to select user groups and that one is based on permissions. We shouldn't check who has permission to view the user groups browser but we would check the permission of each user group.

**Comment by deadcyclo** [comment]
Hey @juliocamarero 

Yes. That is exactly what I implemented for our customer last week. Implemented a lookup from the user group admin portlet in the same manner as the admin-portlet. However, the choose user group view in the user group admin portlet enforces view access on the portlet (also when adding user groups to users). This isn't a problem for our customer. However, I was planning on pushing this, and a similar thing for some of the other targets once I get them done as well, but I'm unsure if this would be a satisfactory solution for everyone, since it does require view access to the user group admin portlet. As far as I can tell, the only other alternative is to implement a custom lookup in the rule itself rather than re-using the lookup view from the user group admin portlet.

**Pull request closed without merging**
